# -*- coding: utf-8 -*-
"""CoffeeMachine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QwjYVocdXJInw1EaH2TSn2Axe4KcHLm7
"""

from abc import ABC, abstractmethod

class Coffee(ABC):

    def __init__(self, coffee, water):
        self.__coffee = coffee
        self.__water = water

    def get_coffee(self):
        return self.__coffee

    def get_water(self):
        return self.__water

    @abstractmethod
    def make_coffee(self):
        pass

    def print_art(self):
        print("Here is your order:")



class Espresso(Coffee):
    def make_coffee(self):
        return f"Espresso: {self.get_coffee()} (strong shot)"



class Americano(Coffee):
    def make_coffee(self):
        return f"Americano: {self.get_coffee()} + {self.get_water()}"



class Latte(Coffee):
    def __init__(self, coffee, water, milk):
        super().__init__(coffee, water)
        self.__milk = milk

    def get_milk(self):
        return self.__milk

    def make_coffee(self):
        return f"Latte: {self.get_coffee()} + {self.get_water()} + {self.get_milk()}"



class Cappuccino(Coffee):
    def __init__(self, coffee, water, milk, foam):
        super().__init__(coffee, water)
        self.__milk = milk
        self.__foam = foam

    def make_coffee(self):
        return f"Cappuccino: {self.get_coffee()} + {self.get_water()} + {self.__milk} + {self.__foam}"



class Mocha(Coffee):
    def __init__(self, coffee, water, chocolate):
        super().__init__(coffee, water)
        self.__chocolate = chocolate

    def make_coffee(self):
        return f"Mocha: {self.get_coffee()} + {self.get_water()} + {self.__chocolate}"



class Frappe(Coffee):
    def __init__(self, coffee, water, ice):
        super().__init__(coffee, water)
        self.__ice = ice

    def make_coffee(self):
        return f"Frappe: {self.get_coffee()} + {self.get_water()} + {self.__ice}"




print("\n☕ Welcome to Coffee Machine ☕")
print("1. Espresso")
print("2. Americano")
print("3. Latte")
print("4. Cappuccino")
print("5. Mocha")
print("6. Frappe")

choice = int(input("Select your coffee (1-6): "))

if choice == 1:
    coffee = Espresso("Coffee", "No Water")
elif choice == 2:
    coffee = Americano("Coffee", "Water")
elif choice == 3:
    coffee = Latte("Coffee", "Water", "Milk")
elif choice == 4:
    coffee = Cappuccino("Coffee", "Water", "Milk", "Foam")
elif choice == 5:
    coffee = Mocha("Coffee", "Water", "Chocolate")
elif choice == 6:
    coffee = Frappe("Coffee", "Water", "Ice")
else:
    print("Invalid choice!")
    exit()

# Output
coffee.print_art()
print(coffee.make_coffee())